verbose = False

set_names = {
        "OP01": "romance-dawn",
        "OP02": "paramount-war",
        "OP03": "pillars-of-strength",
        "OP04": "kingdoms-of-intrigue",
        "OP05": "awakening-of-the-new-era",
        "OP06": "wings-of-the-captain",
        "OP07": "500-years-in-the-future",
        "OP08": "two-legends",
        "OP09": "emperors-in-the-new-world",
        "OP10": "royal-blood",
        "OP11": "a-fist-of-divine-speed",
        "EB01": "extra-booster-memorial-collection",
        "EB02": "premium-booster-the-best",
        "ST01": "starter-deck-1-straw-hat-crew",
        "ST02": "starter-deck-2-worst-generation",
        "ST03": "starter-deck-3-the-seven-warlords-of-the-sea",
        "ST04": "starter-deck-4-animal-kingdom-pirates",
        "ST05": "starter-deck-5-film-edition",
        "ST06": "starter-deck-6-absolute-justice",
        "ST07": "starter-deck-7-big-mom-pirates",
        "ST08": "starter-deck-8-monkeydluffy",
        "ST09": "starter-deck-9-yamato",
        "ST10": "ultra-deck-the-three-captains",
        "ST11": "starter-deck-11-uta",
        "ST12": "starter-deck-12-zoro-and-sanji",
        "ST13": "ultra-deck-the-three-brothers",
        "ST14": "starter-deck-14-3d2y",
        "ST15": "starter-deck-15-red-edwardnewgate",
        "ST16": "starter-deck-16-green-uta",
        "ST17": "starter-deck-17-blue-donquixote-doflamingo",
        "ST18": "starter-deck-18-purple-monkeydluffy",
        "ST19": "starter-deck-19-black-smoker",
        "ST20": "starter-deck-20-yellow-charlotte-katakuri",
        "ST21": "starter-deck-ex-gear-5"
    }